fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    rsyslog:
      repo: 'git://github.com/ghoneycutt/puppet-module-rsyslog.git'
      ref: 'v0.20.0'
    sysklogd:
      repo: 'git://github.com/ghoneycutt/puppet-module-sysklogd.git'
      ref: 'v1.0.0'
    common:
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.3.0'
  symlinks:
    logaggregation: "#{source_dir}"
